# Generated by Django 6.0 on 2025-12-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='remuneração',
            new_name='remuneracao',
        ),
    ]
