# Generated by Django 6.0 on 2025-12-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_remuneração_funcionario_remuneracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='remuneracao',
            new_name='remuneração',
        ),
    ]
