# Generated by Django 6.0 on 2025-12-14 13:45

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_remuneracao_funcionario_remuneração'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
