# Generated by Django 6.0 on 2025-12-14 16:41

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True, unique=True),
        ),
    ]
