# Generated by Django 6.0 on 2025-12-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
    ]
